// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvstuhmbsprhwnyofsor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2c3R1aG1ic3ByaHdueW9mc29yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1Nzc4NDAsImV4cCI6MjA3MDE1Mzg0MH0.Bg826-4_SRNR2NrRxHeDHUelqgCact726noprMCn5NA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});